contact_links:
  - name: Stack Overflow Community
    url: https://stackoverflow.com/questions/tagged/questdb
    about: Ask generic questions or find popular solutions suggested by the QuestDB community