[package]
name = "qdbr"
version = "0.1.0"
edition = "2021"

[lib]
name = "questdbr"
crate-type = ["dylib"]

[dependencies]
jni = "0.21.1"
num-traits = "0.2.18"
parquet2 = { path = "parquet2" }
anyhow = "1.0.86"

[dev-dependencies]
parquet = "51.0.0"
arrow = "51.0.0"
bytes = "1.6.0"
