name: musl Smoke Test
# Testing musl compatibility

on:
  pull_request:
    types: [synchronize, opened, reopened, edited]
    paths:
      - "core/src/main/resources/io/questdb/bin/**"
      - "./core/src/main/bin/**"
  workflow_dispatch:

jobs:
  test-x86-64-musl:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }} # Only run on non-forked PRs
    runs-on: ubuntu-22.04
    container:
      image: alpine:3.22
    steps:
      - name: Install dependencies
        run: apk add --no-cache curl git tar gzip xz nodejs openjdk11-jdk maven bash
      - uses: actions/checkout@v4
      - name: Build distribution
        run: mvn -B clean install -Dmaven.test.skip=true -Pbuild-binaries -pl 'core'
      - name: Unpack distribution
        run: tar -xzf core/target/questdb-*-no-jre-bin.tar.gz
      - name: Start QuestDB
        run: |
          export LD_PRELOAD=${PWD}/core/src/main/bin/linux-x86-64-musl/libjemalloc.so
          JAVA_HOME=/usr/lib/jvm/default-jvm ./questdb-*bin/questdb.sh start
      - name: Query database with curl
        run: |
          curl -G --data-urlencode \
              "query=SELECT * FROM long_sequence(1)" \
              http://localhost:9000/exp
      - name: Upload logs
        if: failure() # Only upload logs if the job failed
        uses: actions/upload-artifact@v4
        with:
          path: ~/.questdb/log/*
          name: logs
          retention-days: 5
  test-aarch64-musl:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }} # Only run on non-forked PRs
    runs-on: ubuntu-22.04-arm
    container:
      image: alpine:3.22
    steps:
      - name: Install dependencies
        run: apk add --no-cache curl git tar gzip xz nodejs openjdk11-jdk maven bash
      - name: Clone repo manually
        run: |
          git config --global --add safe.directory /__w/questdb/questdb
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch --depth 1 origin ${{ github.sha }}
          git checkout FETCH_HEAD
      - name: Build distribution
        run: mvn -B clean install -Dmaven.test.skip=true -Pbuild-binaries -pl 'core'
      - name: Unpack distribution
        run: tar -xzf core/target/questdb-*-no-jre-bin.tar.gz
      - name: Start QuestDB
        run: |
          export LD_PRELOAD=${PWD}/core/src/main/bin/linux-aarch64-musl/libjemalloc.so
          JAVA_HOME=/usr/lib/jvm/default-jvm ./questdb-*bin/questdb.sh start
      - name: Query database with curl
        run: |
          curl -G --data-urlencode \
              "query=SELECT * FROM long_sequence(1)" \
              http://localhost:9000/exp
      - name: Print logs
        if: failure() # Only upload logs if the job failed
        run: |
          cat ~/.questdb/log/*
