name: Parquet Export Compatibility

on:
  pull_request:
    types: [ synchronize, opened, reopened ]
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }} # Only run on non-forked PRs
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build distribution
        run: mvn -B clean install -Dmaven.test.skip=true -Pbuild-binaries -pl '!benchmarks'
      - name: Unpack distribution
        run: tar -xzf core/target/questdb-*-no-jre-bin.tar.gz
      - name: Start QuestDB
        run: ./questdb-*bin/questdb.sh start
      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Run parquet pyarrow22 tests
        run: |
          python3 -m venv venv/parquet_pyarrow22
          source venv/parquet_pyarrow22/bin/activate
          pip install -r compat/src/test/python/requirements_parquet_pyarrow22.txt
          python compat/src/test/python/runner_parquet.py
          deactivate
      - name: Run parquet pyarrow23 tests
        run: |
          python3 -m venv venv/parquet_pyarrow23
          source venv/parquet_pyarrow23/bin/activate
          pip install -r compat/src/test/python/requirements_parquet_pyarrow23.txt
          python compat/src/test/python/runner_parquet.py
          deactivate
      - name: Run parquet duckdb tests
        run: |
          python3 -m venv venv/parquet_duckdb
          source venv/parquet_duckdb/bin/activate
          pip install -r compat/src/test/python/requirements_parquet_duckdb.txt
          python compat/src/test/python/runner_parquet.py
          deactivate
      - name: Run parquet pandas tests
        run: |
          python3 -m venv venv/parquet_pandas
          source venv/parquet_pandas/bin/activate
          pip install -r compat/src/test/python/requirements_parquet_pandas.txt
          python compat/src/test/python/runner_parquet.py
          deactivate
      - name: Run parquet polars tests
        run: |
          python3 -m venv venv/parquet_polars
          source venv/parquet_polars/bin/activate
          pip install -r compat/src/test/python/requirements_parquet_polars.txt
          python compat/src/test/python/runner_parquet.py
          deactivate
      - name: Run parquet pyspark tests
        run: |
          python3 -m venv venv/parquet_pyspark
          source venv/parquet_pyspark/bin/activate
          pip install -r compat/src/test/python/requirements_parquet_pyspark.txt
          python compat/src/test/python/runner_parquet.py
          deactivate
      - name: Stop QuestDB
        run: ./questdb-*bin/questdb.sh stop
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: ~/.questdb/log/*
          name: logs
          retention-days: 5
